apiVersion: v1
kind: Service
metadata:
  name: redis-nodeport
  namespace: lapis-cmn
spec:
  type: NodePort
  selector:
    app: redis-cluster
  ports:
      # By default and for convenience, the `targetPort` is set to the same value as the `port` field.
    - port: 6379
      targetPort: 6379
      # By default and for convenience, the Kubernetes control plane will allocate a port from a range (default: 30000-32767)
      nodePort: 30379
