apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-ssd
  namespace: lapis-cmn
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: alicloud-disk-ssd
