apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJzd3IuY24tZWFzdC0zLm15aHVhd2VpY2xvdWQuY29tIjp7InVzZXJuYW1lIjoiY24tZWFzdC0zQEFMSThLWlZQS1RVVFRFTlBBQ0Q1IiwicGFzc3dvcmQiOiI4NTI4MTNjYWVlMjc0NjdiMDdkYTgyOWJjNThmMDUzNjdlOTQ4OTBmZmYzNGM2ZDVjY2ZjNzk3YTcyZDU2NDgwIiwiYXV0aCI6IlkyNHRaV0Z6ZEMwelFFRk1TVGhMV2xaUVMxUlZWRlJGVGxCQlEwUTFPamcxTWpneE0yTmhaV1V5TnpRMk4ySXdOMlJoT0RJNVltTTFPR1l3TlRNMk4yVTVORGc1TUdabVpqTTBZelprTldOalptTTNPVGRoTnpKa05UWTBPREE9In19fQ==
kind: Secret
metadata:
  name: docker-login-secret
  namespace: lapis-pre
  resourceVersion: "757678"
type: kubernetes.io/dockerconfigjson
