---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: cephfs-sc
  namespace: lapis-cmn
provisioner: ceph.com/cephfs
parameters:
    monitors: 192.168.2.131:6789,192.168.2.132:6789,192.168.2.133:6789
    adminId: admin
    adminSecretName: ceph-admin-secret
    adminSecretNamespace: lapis-cmn
    #    adminSecretNamespace: kube-system
