---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
   name: mysql-sc
   namespace: lapis-cmn
provisioner: kubernetes.io/rbd
parameters:
    monitors: 192.168.2.131:6789,192.168.2.132:6789,192.168.2.133:6789
    adminId: admin
    adminSecretName: ceph-admin-secret
    adminSecretNamespace: kube-system
    pool: rbd-k8s
    userId: admin
    userSecretName: ceph-admin-secret
    userSecretNamespace: lapis-cmn
    #fsType: etx4
    #imageFormat: "2"
    #imageFeatures: "layering"
