---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cephfs-pvc
  namespace: lapis-cmn
  annotations:
    volume.beta.kubernetes.io/storage-class: "cephfs-sc"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi

