apiVersion: v1
kind: Service
metadata:
  name: mysql-headless
  namespace: lapis-cmn
  labels:
    app: mysql
spec:
  ports:
  - name: mysql
    port: 3306
  clusterIP: None
  selector:
    app: mysql
