apiVersion: v1
kind: Service
metadata:
  name: seata-server-svc
  namespace: lapis-cmn
  labels:
    k8s-app: seata-server
spec:
  ports:
    - port: 8091
      protocol: TCP
      name: http
  selector:
    k8s-app: seata-server
