apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitlab-runner-cache
  namespace: devops
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: "manual"
  resources:
    requests:
      storage: 5Gi
  selector:
    matchLabels:
      pv: gitlab-runner-pv
