apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-auto
  namespace: default
  annotations:
    everest.io/disk-volume-type: SAS
  labels:
    failure-domain.beta.kubernetes.io/region: cn-east-3
    failure-domain.beta.kubernetes.io/zone: cn-east-3c
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: csi-disk
