apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: fluentd-es
  name: flu-headless
  namespace: lapis-cmn
spec:
  clusterIP: None
  ports:
  - port: 24224
    protocol: TCP
    targetPort: 24224
  selector:
    k8s-app: fluentd-es
  sessionAffinity: None
  type: ClusterIP
