apiVersion: v1
kind: Service
metadata:
  labels:
    app: fluentd-es-v2.4.0
    name: flu-nodeport
  name: flu-nodeport
  namespace: lapis-cmn
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: cce-service-0
    nodePort: 31594
    port: 24224
    protocol: TCP
    targetPort: 24224
  selector:
    k8s-app: fluentd-es
    kubernetes.io/cluster-service: "true"
    version: v2.4.0
  sessionAffinity: None
  type: NodePort
