apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    addonmanager.kubernetes.io/mode: Reconcile
    k8s-app: fluentd-es
    kubernetes.io/cluster-service: "true"
  name: fluentd-es
  namespace: lapis-cmn
secrets:
- name: fluentd-es-token-kjw9c
