apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: fluentd-es
  labels:
    addonmanager.kubernetes.io/mode: Reconcile
    k8s-app: fluentd-es
    kubernetes.io/cluster-service: "true"
rules:
- apiGroups:
  - ""
  resources:
  - services
  - namespaces
  - endpoints
  - pods
  verbs:
  - get
  - watch
  - list
