apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: rabbitmq
    app.kubernetes.io/name: rabbitmq-cluster-security
    app.kubernetes.io/part-of: rabbitmq
  name: rabbitmq-cluster-security-np
  namespace: lapis-cmn
spec:
  ports:
  - name: amqp
    port: 5672
    protocol: TCP
    targetPort: 5672
    nodePort: 32672
  - name: management
    port: 15672
    protocol: TCP
    targetPort: 15672
    nodePort: 31672
  selector:
    app.kubernetes.io/name: rabbitmq-cluster-security
  type: NodePort

