apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local-path-retain-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path-retain
  resources:
    requests:
      storage: 128Mi
