apiVersion: v1
kind: PersistentVolume
metadata:
  name: test-pv
  namespace: lapis-dev
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  rbd:
    #ceph的monitor节点
    monitors:       
      - 192.168.2.131:6789
      - 192.168.2.132:6789
      - 192.168.2.133:6789
    #ceph的存储池名字
    pool: rbd-test
    #在存储池里创建的image的名字
    image: rbd-s01         
    user: admin
    secretRef:
      name: ceph-secret
    fsType: xfs
    readOnly: false
  persistentVolumeReclaimPolicy: Recycle
